spring:
 application:
  name:
   zuulServer
 zipkin:
  baseUrl: http://ec2-35-182-253-168.ca-central-1.compute.amazonaws.com:9411
server:
 port: 5555
eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://ec2-35-183-62-201.ca-central-1.compute.amazonaws.com:8761/eureka/
zuul:
 routes:
  bookregisterservice: /bookregister/**