spring:
 application:
  name:
   zuulServer
 zipkin:
  baseUrl: http://localhost:9411
server:
 port: 5555
eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
zuul:
 routes:
  bookregisterservice: /bookregister/**